version: '3.1'
services:
  mysqldb:
    platform: linux/amd64
    image: mysql:8.0.30
    container_name: mysqldb
    command: [ '--default-authentication-plugin=mysql_native_password', '--default-storage-engine=innodb' ]
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=datadb
    ports:
      - "13306:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:v2.3.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus-local.yml:/etc/prometheus/prometheus.yml"
    restart: always

  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    ports:
      - 3000:3000
    restart: always